AWSTemplateFormatVersion: 2010-09-09
Description: Tyler Technologies Foundation Database VPC Template
Parameters:
  PublicSubnet1:
    Type: String
  PublicSubnet2:
    Type: String
  PublicSubnet3:
    Type: String
  SecurityGroup:
    Type: String
  VPCID:
    Type: String
Resources:
  DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Subnets available for the RDS DB Instance
      SubnetIds:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
        - !Ref PublicSubnet3

  DBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Database security groups
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: '5432'
          SourceSecurityGroupId: !Ref SecurityGroup
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: '6379'
          SourceSecurityGroupId: !Ref SecurityGroup
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: '1'
          ToPort: '65535'
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VPCID
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref 'AWS::StackName', DBSecurityGroup]]

Outputs:
  DBSecurityGroup:
    Description: DB Security Group
    Value: !Ref DBSecurityGroup
  DBSubnetGroup:
    Description: DB Subnet Group
    Value: !Ref DBSubnetGroup
